export const CONFIG = {
  worldRadius: 40,
  defaultFixedMapId: 'corner_fear',
  defaultMapMode: 'generated',
  generatedMap: {
    family: 'cave',
    seed: 20260415,
    params: {
      floorRate: 0.36,
      loopiness: 0.14,
      chokeDensity: 0.30,
    },
  },
  losEpsilon: 0.05,
  losSampleStep: 0.04,
  perceptionProfiles: {
    player: {
      visionRadius: 7,
      fovHalfAngleDeg: 60,
      adjacentAwareRadius: 1,
      requiresLight: false,
      darkvisionRadius: 0,
      emitsLightRadius: 0,
      detectsLitTargets: true,
    },
    watcher: {
      visionRadius: 6,
      fovHalfAngleDeg: 60,
      adjacentAwareRadius: 1,
      requiresLight: false,
      darkvisionRadius: 0,
      emitsLightRadius: 0,
      detectsLitTargets: true,
    },
  },
  main: {
    tileRadius: 24,
    localRadius: 7,
  },
  sub: {
    tileRadius: 9,
  },
  colors: {
    background: '#0e141a',
    unknown: '#06080b',
    unknownStroke: '#11161c',
    wallVisible: '#3b4b5d',
    wallVisibleStroke: '#536679',
    floorVisible: '#1f394f',
    floorVisibleStroke: '#35546f',
    wallKnown: '#26313c',
    wallKnownStroke: '#394754',
    floorKnown: '#182430',
    floorKnownStroke: '#273744',
    wallNear: '#4d465f',
    wallNearStroke: '#6a6381',
    floorNear: '#2a2940',
    floorNearStroke: '#4b4965',
    player: '#ffd166',
    enemyVisible: '#ff6b6b',
    enemyNear: '#cc7a7a',
    committed: '#ff7b72',
    preview: '#9be564',
    text: '#dbe7f3',
    muted: '#8ca0b3',
  },
};

export const LOCAL_MOVE_LABELS = ['前', '右前', '右後', '後', '左後', '左前'];
